[features]
seeds = false
skip-lint = false

[programs.devnet]
memecoin = "HGVFegegNghXe7J5YyzPhAnBSZZ8YxoQq7ryt8eHesi5"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "HGVFegegNghXe7J5YyzPhAnBSZZ8YxoQq7ryt8eHesi5"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/" 